import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--ascend-border)',
        input: 'var(--ascend-border)',
        ring: 'var(--ascend-brand-500)',
        background: 'var(--ascend-background)',
        foreground: 'var(--ascend-foreground)',
        primary: {
          DEFAULT: 'var(--ascend-brand-500)',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: 'var(--ascend-muted)',
          foreground: 'var(--ascend-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--ascend-danger)',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: 'var(--ascend-muted)',
          foreground: 'var(--ascend-foreground-muted)',
        },
        accent: {
          DEFAULT: 'var(--ascend-accent)',
          foreground: 'var(--ascend-accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--ascend-surface-elevated)',
          foreground: 'var(--ascend-foreground)',
        },
        card: {
          DEFAULT: 'var(--ascend-surface)',
          foreground: 'var(--ascend-foreground)',
        },
        ascend: {
          brand: {
            50: 'var(--ascend-brand-50)',
            100: 'var(--ascend-brand-100)',
            200: 'var(--ascend-brand-200)',
            300: 'var(--ascend-brand-300)',
            400: 'var(--ascend-brand-400)',
            500: 'var(--ascend-brand-500)',
            600: 'var(--ascend-brand-600)',
            700: 'var(--ascend-brand-700)',
            800: 'var(--ascend-brand-800)',
            900: 'var(--ascend-brand-900)',
          },
          success: 'var(--ascend-success)',
          warning: 'var(--ascend-warning)',
          danger: 'var(--ascend-danger)',
          info: 'var(--ascend-info)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        xs: 'var(--ascend-text-xs)',
        sm: 'var(--ascend-text-sm)',
        base: 'var(--ascend-text-base)',
        lg: 'var(--ascend-text-lg)',
        xl: 'var(--ascend-text-xl)',
        '2xl': 'var(--ascend-text-2xl)',
        '3xl': 'var(--ascend-text-3xl)',
        '4xl': 'var(--ascend-text-4xl)',
        '5xl': 'var(--ascend-text-5xl)',
      },
      spacing: {
        1: 'var(--ascend-space-1)',
        2: 'var(--ascend-space-2)',
        3: 'var(--ascend-space-3)',
        4: 'var(--ascend-space-4)',
        5: 'var(--ascend-space-5)',
        6: 'var(--ascend-space-6)',
        8: 'var(--ascend-space-8)',
        10: 'var(--ascend-space-10)',
        12: 'var(--ascend-space-12)',
        16: 'var(--ascend-space-16)',
        20: 'var(--ascend-space-20)',
        24: 'var(--ascend-space-24)',
      },
      borderRadius: {
        none: 'var(--ascend-radius-none)',
        sm: 'var(--ascend-radius-sm)',
        md: 'var(--ascend-radius-md)',
        lg: 'var(--ascend-radius-lg)',
        xl: 'var(--ascend-radius-xl)',
        full: 'var(--ascend-radius-full)',
      },
      boxShadow: {
        sm: 'var(--ascend-shadow-sm)',
        md: 'var(--ascend-shadow-md)',
        lg: 'var(--ascend-shadow-lg)',
        xl: 'var(--ascend-shadow-xl)',
        glow: 'var(--ascend-shadow-glow)',
      },
      transitionDuration: {
        instant: 'var(--ascend-dur-instant)',
        fast: 'var(--ascend-dur-fast)',
        normal: 'var(--ascend-dur-normal)',
        slow: 'var(--ascend-dur-slow)',
        celebrate: 'var(--ascend-dur-celebrate)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ascend-ease-out)',
        'ease-in': 'var(--ascend-ease-in)',
        'ease-in-out': 'var(--ascend-ease-in-out)',
        spring: 'var(--ascend-ease-spring)',
      },
      zIndex: {
        dropdown: 'var(--ascend-z-dropdown)',
        sticky: 'var(--ascend-z-sticky)',
        navbar: 'var(--ascend-z-navbar)',
        modal: 'var(--ascend-z-modal)',
        toast: 'var(--ascend-z-toast)',
        tooltip: 'var(--ascend-z-tooltip)',
        overlay: 'var(--ascend-z-overlay)',
        max: 'var(--ascend-z-max)',
      },
      opacity: {
        5: 'var(--ascend-opacity-5)',
        10: 'var(--ascend-opacity-10)',
        20: 'var(--ascend-opacity-20)',
        30: 'var(--ascend-opacity-30)',
        40: 'var(--ascend-opacity-40)',
        50: 'var(--ascend-opacity-50)',
        60: 'var(--ascend-opacity-60)',
        70: 'var(--ascend-opacity-70)',
        80: 'var(--ascend-opacity-80)',
        90: 'var(--ascend-opacity-90)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'xp-pulse': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.2)' },
          '100%': { transform: 'scale(1)' },
        },
        progress: {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.5s linear infinite',
        'fade-in': 'fade-in var(--ascend-dur-normal) var(--ascend-ease-out)',
        'slide-up': 'slide-up var(--ascend-dur-slow) var(--ascend-ease-out)',
        'slide-down': 'slide-down var(--ascend-dur-fast) var(--ascend-ease-out)',
        'scale-in': 'scale-in var(--ascend-dur-normal) var(--ascend-ease-out)',
        'xp-pulse': 'xp-pulse var(--ascend-dur-slow) var(--ascend-ease-out)',
        progress: 'progress var(--ascend-dur-slow) var(--ascend-ease-out)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
