from typing import List, Optional, Protocol

from ascend.domain.builder import Builder
from ascend.domain.mission import Mission
from ascend.domain.evidence import Evidence
from ascend.domain.competency import Competency
from ascend.domain.journey import Journey


class BuilderRepository(Protocol):
    def save(self, builder: Builder) -> None: ...
    def get(self, builder_id: str) -> Builder: ...
    def get_by_username(self, username: str) -> Optional[Builder]: ...
    def list(self) -> List[Builder]: ...


class MissionRepository(Protocol):
    def save(self, mission: Mission) -> None: ...
    def get(self, mission_id: str) -> Mission: ...
    def list_by_journey(self, journey_id: str) -> List[Mission]: ...


class EvidenceRepository(Protocol):
    def save(self, evidence: Evidence) -> None: ...
    def get(self, evidence_id: str) -> Evidence: ...
    def list_by_builder(self, builder_id: str) -> List[Evidence]: ...


class CompetencyRepository(Protocol):
    def save(self, competency: Competency) -> None: ...
    def get(self, competency_id: str) -> Competency: ...
    def list_by_builder(self, builder_id: str) -> List[Competency]: ...


class JourneyRepository(Protocol):
    def save(self, journey: Journey) -> None: ...
    def get(self, journey_id: str) -> Journey: ...
    def list(self) -> List[Journey]: ...
